#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, print_function

import sys
import argparse

import stitcher
from stitcher.profiles.profile import Profile


parser = argparse.ArgumentParser(
    description='Stitch together Messenger conversation screenshots')
parser.add_argument('profile',
                    help='The identifier of the profile to use for stitching')
parser.add_argument('outfile',
                    help='The name of the file to save the composition to')
parser.add_argument('images', nargs='+', help='Paths of images to combine')
args = parser.parse_args()

try:
    profile = Profile.from_identifier(args.profile)
    image = stitcher.join(args.images, profile)
    image.save(args.outfile)
except ValueError as e:
    print(e.message, file=sys.stderr)
